### ISSUE TITLE
pip install pip-requires.txt fails on UoW

### ISSUE THREAD

**Issue by lorenjerickson** [aspiers/ly2video#62]
This may be a non-starter, and if so that's okay I guess.  I'm trying to install and run ly2video on UoW (Ubuntu on Windows), which is based on trusty-tahir.   All the dependencies installed fine via `apt-get install`.  I also installed latest lilypond without errors. 

I got to the step of installing the patched python-midi via `pip-requires.txt` and got the following error.

```
loren@OFFICE-PC:/mnt/c/Users/loren/Downloads/ly2video/ly2video-master$ pip install --user -r pip-requires.txt
Downloading/unpacking PIL==1.1.7 (from -r pip-requires.txt (line 1))
  Could not find any downloads that satisfy the requirement PIL==1.1.7 (from -r pip-requires.txt (line 1))
Cleaning up...
No distributions at all found for PIL==1.1.7 (from -r pip-requires.txt (line 1))
Storing debug log for failure in /tmp/tmpaGhCP5
```

I'm not a python dev, and have no idea what this means.  So I tried installing python-midi via `pip` directly, figuring I could live with a "significant temp calculation bug" just to see this work, and it did install.  

The ly2video install, which happened very quickly, also seemed to go okay.  Nothing obvious in the output.  When I run the app `./ly2video --help`, I get the following: 

```
loren@OFFICE-PC:/usr/local/bin$ ./ly2video.py --help
Traceback (most recent call last):
  File "./ly2video.py", line 44, in <module>
    from ly.tokenize import MusicTokenizer, Tokenizer
ImportError: No module named ly.tokenize
```

Looks like I have both Pythin 2.7 and 3.4 installed.  Not sure if that's relevant. 

Any ideas on how to get this to work?

**Comment by aspiers** [comment]
> I'm not a python dev, and have no idea what this means.

It means that `ly2video` requires version 1.1.7 of [PIL](http://www.pythonware.com/products/pil/), but that doesn't seem to be available to install via `pip`.  I have no idea how UoW works but that problem is nothing to do with `ly2video` so you'll have to rely on help from the UoW and PIL communities.

> When I run the app `./ly2video --help`, I get the following:

Hmm, it seems that there's probably a bug in the `README.md`.  If you've installed it by following the instructions, i.e. via

    python2 setup.py install --root=INSTALLATION_DIR

then `ly2video` should be installed under `INSTALLATION_DIR`, so you need to run it from there in order to pick up the correct libraries required.  You can't just run it directly from the source repo.

But until you have PIL installed, there's no point trying to run it, because PIL is absolutely required in order to generate video frames.

**Comment by aspiers** [comment]
Hmm, I just noticed this same issue for me when trying to install PIL from `pip` instead of via rpm.  `pip search` shows that [only 1.1.6 is available on PyPI](https://pypi.org/project/PIL/), which is bizarre ...

**Comment by aspiers** [comment]
Also, PIL was last released in 2009, so it's a total dead-end :-(

**Comment by aspiers** [comment]
We switched to Pillow so this should be solved now.
