### ISSUE TITLE
An AUR dependency does not exist

### ISSUE THREAD

**Issue by skuzzymiglet** [aspiers/ly2video#89]
`ly2video-git` in the AUR depends on `python2-pypdf`, which does not exist. The correct package is `python2-pypdf2-git`. The dependency needs to be updated

**Comment by aspiers** [comment]
Thanks for the report; however it sounds like this issue relates to the downstream AUR packages. There is no mention of `pypdf` in this repository, so there is nothing to fix here.

Therefore I recommend that you report the bug to Arch Linux for the package maintainer there to fix. I've never personally used Arch so I don't know where this dependency is stored, although I do see it here: https://aur.archlinux.org/packages/ly2video-git/

I'm not even sure why the AUR package would require anything to do with PDFs, since ly2video doesn't use the PDF format at all.

Closing, but I'm happy to reopen if I misunderstood something.
